AllCops:
  Exclude:
    - bin/*
    - tmp/**/*
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing

Metrics/LineLength:
  Exclude:
    - spec/**/*_spec.rb
